version: "3.8"
services:
  users_service:
    build: ./users_service
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@users_db:5432/users_db
    depends_on:
      - users_db

  cars_service:
    build: ./cars_service
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgresql://user:password@cars_db:5432/cars_db
    depends_on:
      - cars_db
      - redis

  rentals_service:
    build: ./rentals_service
    ports:
      - "8003:8003"
    environment:
      - DATABASE_URL=postgresql://user:password@rentals_db:5432/rentals_db
    depends_on:
      - rentals_db
      - redis

  gateway_service:
    build: ./gateway_service
    ports:
      - "8002:8002"
    depends_on:
      - users_service
      - cars_service
      - rentals_service

  users_db:
    image: postgres:13
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=users_db
    volumes:
      - users_data:/var/lib/postgresql/data

  cars_db:
    image: postgres:13
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=cars_db
    volumes:
      - cars_data:/var/lib/postgresql/data

  rentals_db:
    image: postgres:13
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=rentals_db
    volumes:
      - rentals_data:/var/lib/postgresql/data

  redis:
    image: redis:6
    volumes:
      - redis_data:/data

volumes:
  users_data:
  cars_data:
  rentals_data:
  redis_data:
